### ISSUE TITLE
Add dependencies to cpp 

### ISSUE THREAD

**Issue by uselessgoddess** [linksplatform/Documentation#19]
**We can add additional dependencies that are needed for C++?**
![Dependencies](https://user-images.githubusercontent.com/68294279/116923115-e4c5be80-ac5e-11eb-91d2-0f9d3bb2ea5f.png)

**Comment by Konard** [comment]
Yes, we should have dependency try for C++ version.

**Comment by uselessgoddess** [comment]
closed in #24
